export const AnswerFilters = [
  { name: "Highest Upvotes", value: "highestUpvotes" },
  { name: "Lowest Upvotes", value: "lowestUpvotes" },
  { name: "Most Recent", value: "recent" },
  { name: "Oldest", value: "old" },
];

export const UserFilters = [
  { name: "New Users", value: "new_users" },
  { name: "Old Users", value: "old_users" },
  { name: "Top Contributors", value: "top_contributors" },
];

export const QuestionFilters = [
  { name: "Most Recent", value: "most_recent" },
  { name: "Oldest", value: "oldest" },
  { name: "Most Voted", value: "most_voted" },
  { name: "Most Viewed", value: "most_viewed" },
  { name: "Most Answered", value: "most_answered" },
];

export const TagFilters = [
  { name: "Popular", value: "popular" },
  { name: "Recent", value: "recent" },
  { name: "Name", value: "name" },
  { name: "Old", value: "old" },
];

export const HomePageFilters = [
  { name: "Newest", value: "newest" },
  { name: "Recommended", value: "recommended" },
  { name: "Frequent", value: "frequent" },
  { name: "Unanswered", value: "unanswered" },
];

export const GlobalSearchFilters = [
  { name: "Question", value: "question" },
  { name: "Answer", value: "answer" },
  { name: "User", value: "user" },
  { name: "Tag", value: "tag" },
];

export const AllCountriesFilters = [
  { name: "Afghanistan", value: "afghanistan", code: "AF" },
  { name: "Albania", value: "albania", code: "AL" },
  { name: "Algeria", value: "algeria", code: "DZ" },
  { name: "Andorra", value: "andorra", code: "AD" },
  { name: "Angola", value: "angola", code: "AO" },
  { name: "Antigua and Barbuda", value: "antigua and barbuda", code: "AG" },
  { name: "Argentina", value: "argentina", code: "AR" },
  { name: "Armenia", value: "armenia", code: "AM" },
  { name: "Australia", value: "australia", code: "AU" },
  { name: "Austria", value: "austria", code: "AT" },
  { name: "Azerbaijan", value: "azerbaijan", code: "AZ" },
  { name: "Bahamas", value: "bahamas", code: "BS" },
  { name: "Bahrain", value: "bahrain", code: "BH" },
  { name: "Bangladesh", value: "bangladesh", code: "BD" },
  { name: "Barbados", value: "barbados", code: "BB" },
  { name: "Belarus", value: "belarus", code: "BY" },
  { name: "Belgium", value: "belgium", code: "BE" },
  { name: "Belize", value: "belize", code: "BZ" },
  { name: "Benin", value: "benin", code: "BJ" },
  { name: "Bhutan", value: "bhutan", code: "BT" },
  { name: "Bolivia", value: "bolivia", code: "BO" },
  {
    name: "Bosnia and Herzegovina",
    value: "bosnia and herzegovina",
    code: "BA",
  },
  { name: "Botswana", value: "botswana", code: "BW" },
  { name: "Brazil", value: "brazil", code: "BR" },
  { name: "Brunei", value: "brunei", code: "BN" },
  { name: "Bulgaria", value: "bulgaria", code: "BG" },
  { name: "Burkina Faso", value: "burkina faso", code: "BF" },
  { name: "Burundi", value: "burundi", code: "BI" },
  { name: "Cabo Verde", value: "cabo verde", code: "CV" },
  { name: "Cambodia", value: "cambodia", code: "KH" },
  { name: "Cameroon", value: "cameroon", code: "CM" },
  { name: "Canada", value: "canada", code: "CA" },
  {
    name: "Central African Republic",
    value: "central african republic",
    code: "CF",
  },
  { name: "Chad", value: "chad", code: "TD" },
  { name: "Chile", value: "chile", code: "CL" },
  { name: "China", value: "china", code: "CN" },
  { name: "Colombia", value: "colombia", code: "CO" },
  { name: "Comoros", value: "comoros", code: "KM" },
  {
    name: "Congo (Congo-Brazzaville)",
    value: "congo (congo-brazzaville)",
    code: "CG",
  },
  { name: "Costa Rica", value: "costa rica", code: "CR" },
  { name: "Croatia", value: "croatia", code: "HR" },
  { name: "Cuba", value: "cuba", code: "CU" },
  { name: "Cyprus", value: "cyprus", code: "CY" },
  {
    name: "Czechia (Czech Republic)",
    value: "czechia (czech republic)",
    code: "CZ",
  },
  {
    name: "Democratic Republic of the Congo",
    value: "democratic republic of the congo",
    code: "CD",
  },
  { name: "Denmark", value: "denmark", code: "DK" },
  { name: "Djibouti", value: "djibouti", code: "DJ" },
  { name: "Dominica", value: "dominica", code: "DM" },
  { name: "Dominican Republic", value: "dominican republic", code: "DO" },
  { name: "Ecuador", value: "ecuador", code: "EC" },
  { name: "Egypt", value: "egypt", code: "EG" },
  { name: "El Salvador", value: "el salvador", code: "SV" },
  { name: "Equatorial Guinea", value: "equatorial guinea", code: "GQ" },
  { name: "Eritrea", value: "eritrea", code: "ER" },
  { name: "Estonia", value: "estonia", code: "EE" },
  {
    name: "Eswatini (fmr. Swaziland)",
    value: "eswatini (fmr. swaziland)",
    code: "SZ",
  },
  { name: "Ethiopia", value: "ethiopia", code: "ET" },
  { name: "Fiji", value: "fiji", code: "FJ" },
  { name: "Finland", value: "finland", code: "FI" },
  { name: "France", value: "france", code: "FR" },
  { name: "Gabon", value: "gabon", code: "GA" },
  { name: "Gambia", value: "gambia", code: "GM" },
  { name: "Georgia", value: "georgia", code: "GE" },
  { name: "Germany", value: "germany", code: "DE" },
  { name: "Ghana", value: "ghana", code: "GH" },
  { name: "Greece", value: "greece", code: "GR" },
  { name: "Grenada", value: "grenada", code: "GD" },
  { name: "Guatemala", value: "guatemala", code: "GT" },
  { name: "Guinea", value: "guinea", code: "GN" },
  { name: "Guinea-Bissau", value: "guinea-bissau", code: "GW" },
  { name: "Guyana", value: "guyana", code: "GY" },
  { name: "Haiti", value: "haiti", code: "HT" },
  { name: "Honduras", value: "honduras", code: "HN" },
  { name: "Hungary", value: "hungary", code: "HU" },
  { name: "Iceland", value: "iceland", code: "IS" },
  { name: "India", value: "india", code: "IN" },
  { name: "Indonesia", value: "indonesia", code: "ID" },
  { name: "Iran", value: "iran", code: "IR" },
  { name: "Iraq", value: "iraq", code: "IQ" },
  { name: "Ireland", value: "ireland", code: "IE" },
  { name: "Israel", value: "israel", code: "IL" },
  { name: "Italy", value: "italy", code: "IT" },
  { name: "Ivory Coast", value: "ivory coast", code: "CI" },
  { name: "Jamaica", value: "jamaica", code: "JM" },
  { name: "Japan", value: "japan", code: "JP" },
  { name: "Jordan", value: "jordan", code: "JO" },
  { name: "Kazakhstan", value: "kazakhstan", code: "KZ" },
  { name: "Kenya", value: "kenya", code: "KE" },
  { name: "Kiribati", value: "kiribati", code: "KI" },
  { name: "Kosovo", value: "kosovo", code: "XK" },
  { name: "Kuwait", value: "kuwait", code: "KW" },
  { name: "Kyrgyzstan", value: "kyrgyzstan", code: "KG" },
  { name: "Laos", value: "laos", code: "LA" },
  { name: "Latvia", value: "latvia", code: "LV" },
  { name: "Lebanon", value: "lebanon", code: "LB" },
  { name: "Lesotho", value: "lesotho", code: "LS" },
  { name: "Liberia", value: "liberia", code: "LR" },
  { name: "Libya", value: "libya", code: "LY" },
  { name: "Liechtenstein", value: "liechtenstein", code: "LI" },
  { name: "Lithuania", value: "lithuania", code: "LT" },
  { name: "Luxembourg", value: "luxembourg", code: "LU" },
  { name: "Madagascar", value: "madagascar", code: "MG" },
  { name: "Malawi", value: "malawi", code: "MW" },
  { name: "Malaysia", value: "malaysia", code: "MY" },
  { name: "Maldives", value: "maldives", code: "MV" },
  { name: "Mali", value: "mali", code: "ML" },
  { name: "Malta", value: "malta", code: "MT" },
  { name: "Marshall Islands", value: "marshall islands", code: "MH" },
  { name: "Mauritania", value: "mauritania", code: "MR" },
  { name: "Mauritius", value: "mauritius", code: "MU" },
  { name: "Mexico", value: "mexico", code: "MX" },
  { name: "Micronesia", value: "micronesia", code: "FM" },
  { name: "Moldova", value: "moldova", code: "MD" },
  { name: "Monaco", value: "monaco", code: "MC" },
  { name: "Mongolia", value: "mongolia", code: "MN" },
  { name: "Montenegro", value: "montenegro", code: "ME" },
  { name: "Morocco", value: "morocco", code: "MA" },
  { name: "Mozambique", value: "mozambique", code: "MZ" },
  { name: "Myanmar", value: "myanmar", code: "MM" },
  { name: "Namibia", value: "namibia", code: "NA" },
  { name: "Nauru", value: "nauru", code: "NR" },
  { name: "Nepal", value: "nepal", code: "NP" },
  { name: "Netherlands", value: "netherlands", code: "NL" },
  { name: "New Zealand", value: "new zealand", code: "NZ" },
  { name: "Nicaragua", value: "nicaragua", code: "NI" },
  { name: "Niger", value: "niger", code: "NE" },
  { name: "Nigeria", value: "nigeria", code: "NG" },
  { name: "North Korea", value: "north korea", code: "KP" },
  { name: "North Macedonia", value: "north macedonia", code: "MK" },
  { name: "Norway", value: "norway", code: "NO" },
  { name: "Oman", value: "oman", code: "OM" },
  { name: "Pakistan", value: "pakistan", code: "PK" },
  { name: "Palau", value: "palau", code: "PW" },
  { name: "Palestine State", value: "palestine state", code: "PS" },
  { name: "Panama", value: "panama", code: "PA" },
  { name: "Papua New Guinea", value: "papua new guinea", code: "PG" },
  { name: "Paraguay", value: "paraguay", code: "PY" },
  { name: "Peru", value: "peru", code: "PE" },
  { name: "Philippines", value: "philippines", code: "PH" },
  { name: "Poland", value: "poland", code: "PL" },
  { name: "Portugal", value: "portugal", code: "PT" },
  { name: "Qatar", value: "qatar", code: "QA" },
  { name: "Romania", value: "romania", code: "RO" },
  { name: "Russia", value: "russia", code: "RU" },
  { name: "Rwanda", value: "rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", value: "saint kitts and nevis", code: "KN" },
  { name: "Saint Lucia", value: "saint lucia", code: "LC" },
  {
    name: "Saint Vincent and the Grenadines",
    value: "saint vincent and the grenadines",
    code: "VC",
  },
  { name: "Samoa", value: "samoa", code: "WS" },
  { name: "San Marino", value: "san marino", code: "SM" },
  { name: "Sao Tome and Principe", value: "sao tome and principe", code: "ST" },
  { name: "Saudi Arabia", value: "saudi arabia", code: "SA" },
  { name: "Senegal", value: "senegal", code: "SN" },
  { name: "Serbia", value: "serbia", code: "RS" },
  { name: "Seychelles", value: "seychelles", code: "SC" },
  { name: "Sierra Leone", value: "sierra leone", code: "SL" },
  { name: "Singapore", value: "singapore", code: "SG" },
  { name: "Slovakia", value: "slovakia", code: "SK" },
  { name: "Slovenia", value: "slovenia", code: "SI" },
  { name: "Solomon Islands", value: "solomon islands", code: "SB" },
  { name: "Somalia", value: "somalia", code: "SO" },
  { name: "South Africa", value: "south africa", code: "ZA" },
  { name: "South Korea", value: "south korea", code: "KR" },
  { name: "South Sudan", value: "south sudan", code: "SS" },
  { name: "Spain", value: "spain", code: "ES" },
  { name: "Sri Lanka", value: "sri lanka", code: "LK" },
  { name: "Sudan", value: "sudan", code: "SD" },
  { name: "Suriname", value: "suriname", code: "SR" },
  { name: "Sweden", value: "sweden", code: "SE" },
  { name: "Switzerland", value: "switzerland", code: "CH" },
  { name: "Syria", value: "syria", code: "SY" },
  { name: "Tajikistan", value: "tajikistan", code: "TJ" },
  { name: "Tanzania", value: "tanzania", code: "TZ" },
  { name: "Thailand", value: "thailand", code: "TH" },
  { name: "Timor-Leste", value: "timor-leste", code: "TL" },
  { name: "Togo", value: "togo", code: "TG" },
  { name: "Tonga", value: "tonga", code: "TO" },
  { name: "Trinidad and Tobago", value: "trinidad and tobago", code: "TT" },
  { name: "Tunisia", value: "tunisia", code: "TN" },
  { name: "Turkey", value: "turkey", code: "TR" },
  { name: "Turkmenistan", value: "turkmenistan", code: "TM" },
  { name: "Tuvalu", value: "tuvalu", code: "TV" },
  { name: "Uganda", value: "uganda", code: "UG" },
  { name: "Ukraine", value: "ukraine", code: "UA" },
  { name: "United Arab Emirates", value: "united arab emirates", code: "AE" },
  { name: "United Kingdom", value: "united kingdom", code: "GB" },
  {
    name: "United States of America",
    value: "united states of america",
    code: "US",
  },
  { name: "Uruguay", value: "uruguay", code: "UY" },
  { name: "Uzbekistan", value: "uzbekistan", code: "UZ" },
  { name: "Vanuatu", value: "vanuatu", code: "VU" },
  { name: "Vatican City", value: "vatican city", code: "VA" },
  { name: "Venezuela", value: "venezuela", code: "VE" },
  { name: "Vietnam", value: "vietnam", code: "VN" },
  { name: "Yemen", value: "yemen", code: "YE" },
  { name: "Zambia", value: "zambia", code: "ZM" },
  { name: "Zimbabwe", value: "zimbabwe", code: "ZW" },
];
